"""Add new tables

Revision ID: 7ef64fb01c5b
Revises: 61690c62e11e
Create Date: 2025-05-28 14:34:09.043655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef64fb01c5b'
down_revision: Union[str, None] = '61690c62e11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_constraint('uq_customers_email', 'customers', type_='unique')
    op.add_column('employees', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('date_employed', sa.Date(), nullable=False))
    op.alter_column('order_details', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_details', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_details', 'quantity')
    op.drop_column('order_details', 'price')
    op.add_column('orders', sa.Column('total_price', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('time', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'description')
    op.add_column('products', sa.Column('type', sa.String(), nullable=False))
    op.add_column('products', sa.Column('in_stock', sa.Integer(), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('products', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('suppliers', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('contact_phone', sa.String(), nullable=True))
    op.drop_column('suppliers', 'contact_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact_info', sa.VARCHAR(), nullable=True))
    op.drop_column('suppliers', 'contact_phone')
    op.drop_column('suppliers', 'contact_email')
    op.drop_column('suppliers', 'contact_name')
    op.alter_column('products', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('products', 'in_stock')
    op.drop_column('products', 'type')
    op.add_column('orders', sa.Column('description', sa.VARCHAR(), nullable=False))
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'time')
    op.drop_column('orders', 'total_price')
    op.add_column('order_details', sa.Column('price', sa.FLOAT(), nullable=False))
    op.add_column('order_details', sa.Column('quantity', sa.INTEGER(), nullable=False))
    op.alter_column('order_details', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_details', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employees', 'date_employed')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'age')
    op.create_unique_constraint('uq_customers_email', 'customers', ['email'])
    op.drop_column('customers', 'phone_number')
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
